name: dicom
description: Dependency Injection library
version: 0.0.2
homepage: https://github.com/koldoon/dicom

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  logecom: ^0.0.5

dev_dependencies:
  dartdoc:


